server:
  port: 8080
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloudpayment?serverTimezone=UTC #useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: rootroot

  rabbitmq:
    host: localhost
    username: guest
    password: guest
    port: 5672

mybatis:
  configuration:
    map-underscore-to-camel-case: true


logging:
  level:
    com.payment.transfer.module.mapper: debug
