server:
  port: 8080
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloudpayment?serverTimezone=UTC #useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: rootroot

mybatis:
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    com.payment.transfer.module.mapper: debug
